"""
Database initialization and connection pool management for OCI Autonomous Database.
"""
import oracledb
from api.config import get_settings

# Module-level pool reference
_pool: oracledb.ConnectionPool | None = None


def init_pool() -> oracledb.ConnectionPool:
    """Create and store a connection pool. Call once at app startup."""
    global _pool
    if _pool is not None:
        return _pool

    settings = get_settings()

    _pool = oracledb.create_pool(
        user=settings.db_user,
        password=settings.db_password,
        dsn=settings.db_dsn,
        config_dir=settings.wallet_location,
        wallet_location=settings.wallet_location,
        wallet_password=settings.db_password,
        min=1,
        max=5,
        increment=1,
    )
    return _pool


def get_pool() -> oracledb.ConnectionPool:
    """Return existing pool or raise."""
    if _pool is None:
        raise RuntimeError("Database pool is not initialized. Call init_pool() first.")
    return _pool


def get_connection() -> oracledb.Connection:
    """Acquire a connection from the pool."""
    return get_pool().acquire()


def release_connection(conn: oracledb.Connection) -> None:
    """Release connection back to the pool."""
    get_pool().release(conn)


def close_pool() -> None:
    """Close the pool. Call at app shutdown."""
    global _pool
    if _pool is not None:
        _pool.close(force=True)
        _pool = None


# ─── Schema DDL ───

_TABLE_DDL = [
    """
    CREATE TABLE users (
        id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        supabase_user_id  VARCHAR2(128) UNIQUE NOT NULL,
        email             VARCHAR2(320),
        username          VARCHAR2(100),
        avatar_url        VARCHAR2(1000),
        created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE raw_files (
        id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id            NUMBER NOT NULL,
        game               VARCHAR2(16) NOT NULL,
        file_type          VARCHAR2(32) NOT NULL,
        original_name      VARCHAR2(500) NOT NULL,
        object_key         VARCHAR2(1000) NOT NULL,
        sha256             VARCHAR2(128) NOT NULL,
        size_bytes         NUMBER NOT NULL,
        mime_type          VARCHAR2(200),
        upload_status      VARCHAR2(32) DEFAULT 'uploaded',
        created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE laps (
        id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id            NUMBER NOT NULL,
        game               VARCHAR2(16) NOT NULL,
        track              VARCHAR2(200),
        car                VARCHAR2(200),
        lap_number         NUMBER,
        lap_time_ms        NUMBER,
        is_valid           NUMBER(1) DEFAULT 1,
        is_public          NUMBER(1) DEFAULT 0,
        setup_raw_file_id  NUMBER,
        recorded_at        TIMESTAMP,
        uploaded_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE telemetry (
        lap_id             NUMBER PRIMARY KEY,
        points_json        CLOB NOT NULL
    )
    """,
    """
    CREATE TABLE ai_analysis (
        id                         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        lap_id                     NUMBER NOT NULL,
        overall_summary            CLOB,
        estimated_improvement_ms   NUMBER,
        corners_json               CLOB,
        created_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE import_jobs (
        id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id            NUMBER NOT NULL,
        raw_file_id        NUMBER NOT NULL,
        game               VARCHAR2(16) NOT NULL,
        status             VARCHAR2(32) NOT NULL,
        total_laps         NUMBER,
        imported_laps      NUMBER,
        failed_laps        NUMBER,
        warnings_json      CLOB,
        created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        finished_at        TIMESTAMP
    )
    """,
    """
    CREATE TABLE share_codes (
        code               VARCHAR2(32) PRIMARY KEY,
        lap_id_a           NUMBER NOT NULL,
        lap_id_b           NUMBER NOT NULL,
        created_by         NUMBER NOT NULL,
        expires_at         TIMESTAMP,
        view_count         NUMBER DEFAULT 0,
        created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
]


def init_tables() -> None:
    """Create tables if they don't exist."""
    conn = get_connection()
    try:
        cursor = conn.cursor()
        for ddl in _TABLE_DDL:
            try:
                cursor.execute(ddl)
                print("✓ Table created successfully.")
            except oracledb.DatabaseError as e:
                (error_obj,) = e.args
                if error_obj.code == 955:  # ORA-00955: table already exists
                    pass
                else:
                    print(f"✗ DDL error: {error_obj.message}")
        conn.commit()
        cursor.close()
        print("Database schema initialization complete.")
    finally:
        release_connection(conn)


if __name__ == "__main__":
    init_pool()
    init_tables()
