import os
import oracledb
from dotenv import load_dotenv

load_dotenv()

DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_DSN = os.getenv("DB_DSN")
WALLET_LOCATION = os.getenv("WALLET_LOCATION")

def get_connection():
    if not all([DB_USER, DB_PASSWORD, DB_DSN, WALLET_LOCATION]):
        raise ValueError("Database configuration environment variables are missing.")

    return oracledb.connect(
        user=DB_USER,
        password=DB_PASSWORD,
        dsn=DB_DSN,
        config_dir=WALLET_LOCATION,
        wallet_location=WALLET_LOCATION,
        wallet_password=DB_PASSWORD
    )

def init_db():
    try:
        conn = get_connection()
        cursor = conn.cursor()
    except Exception as e:
        print("Failed to connect to the database:", e)
        return

    tables = [
        """
        CREATE TABLE users (
            id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            supabase_user_id  VARCHAR2(128) UNIQUE NOT NULL,
            email             VARCHAR2(320),
            username          VARCHAR2(100),
            avatar_url        VARCHAR2(1000),
            created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE raw_files (
            id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id            NUMBER NOT NULL,
            game               VARCHAR2(16) NOT NULL,
            file_type          VARCHAR2(32) NOT NULL,
            original_name      VARCHAR2(500) NOT NULL,
            object_key         VARCHAR2(1000) NOT NULL,
            sha256             VARCHAR2(128) NOT NULL,
            size_bytes         NUMBER NOT NULL,
            mime_type          VARCHAR2(200),
            upload_status      VARCHAR2(32) DEFAULT 'uploaded',
            created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE laps (
            id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id            NUMBER NOT NULL,
            game               VARCHAR2(16) NOT NULL,
            track              VARCHAR2(200),
            car                VARCHAR2(200),
            lap_number         NUMBER,
            lap_time_ms        NUMBER,
            is_valid           NUMBER(1) DEFAULT 1,
            is_public          NUMBER(1) DEFAULT 0,
            setup_raw_file_id  NUMBER,
            recorded_at        TIMESTAMP,
            uploaded_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE telemetry (
            lap_id             NUMBER PRIMARY KEY,
            points_json        CLOB NOT NULL
        )
        """,
        """
        CREATE TABLE ai_analysis (
            id                         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            lap_id                     NUMBER NOT NULL,
            overall_summary            CLOB,
            estimated_improvement_ms   NUMBER,
            corners_json               CLOB,
            created_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE import_jobs (
            id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id            NUMBER NOT NULL,
            raw_file_id        NUMBER NOT NULL,
            game               VARCHAR2(16) NOT NULL,
            status             VARCHAR2(32) NOT NULL,
            total_laps         NUMBER,
            imported_laps      NUMBER,
            failed_laps        NUMBER,
            warnings_json      CLOB,
            created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            finished_at        TIMESTAMP
        )
        """,
        """
        CREATE TABLE share_codes (
            code               VARCHAR2(32) PRIMARY KEY,
            lap_id_a           NUMBER NOT NULL,
            lap_id_b           NUMBER NOT NULL,
            created_by         NUMBER NOT NULL,
            expires_at         TIMESTAMP,
            view_count         NUMBER DEFAULT 0,
            created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    ]

    for ddl in tables:
        try:
            cursor.execute(ddl)
            print("Successfully created a table.")
        except oracledb.DatabaseError as e:
            error_obj, = e.args
            if error_obj.code == 955:
                print("Table already exists, skipping...")
            else:
                print(f"Error executing DDL: {error_obj.message}")

    conn.commit()
    cursor.close()
    conn.close()
    print("Database initialization complete.")

if __name__ == "__main__":
    init_db()
